# Generated by Django 5.2.1 on 2025-05-24 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("humans", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="human",
            options={"ordering": ["first_name"]},
        ),
    ]
