# Generated by Django 5.2.1 on 2025-05-24 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("humans", "0002_alter_human_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="human",
            options={},
        ),
    ]
