# Generated by Django 5.2.1 on 2025-05-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("humans", "0003_alter_human_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="human",
            name="avatar",
            field=models.URLField(blank=True, null=True, verbose_name="avatar"),
        ),
    ]
